#!/usr/bin/env bash
set -euo pipefail

REPO_ROOT=$(cd "$(dirname "${BASH_SOURCE[0]}")/.." && pwd)
LOG_DIR="$REPO_ROOT/logs/compound"
TIMESTAMP=$(date +"%Y%m%d-%H%M%S")
LOG_JSON="$LOG_DIR/auto-compound-$TIMESTAMP.jsonl"

mkdir -p "$LOG_DIR"

cd "$REPO_ROOT"

# Allow untracked logs/review notes without blocking automation
DIRTY=$(git status --porcelain)
DIRTY_FILTERED=$(echo "$DIRTY" | rg -v "^\?\? (logs/|docs/review/)" || true)
if [[ -n "$DIRTY_FILTERED" ]]; then
  echo "Working tree dirty; aborting auto-compound." >&2
  echo "$DIRTY_FILTERED" >&2
  exit 1
fi

git checkout main
git pull --rebase

PICK_OUTPUT=$("$REPO_ROOT/scripts/compound-pick-ticket.sh" || true)
if [[ -z "$PICK_OUTPUT" ]]; then
  echo "No ready sv tasks. Exiting." >&2
  exit 0
fi

IFS=$'\t' read -r TICKET_ID TICKET_TITLE <<< "$PICK_OUTPUT"

if [[ -z "$TICKET_ID" || -z "$TICKET_TITLE" ]]; then
  echo "Failed to parse task selection." >&2
  exit 1
fi

slugify() {
  echo "$1" | tr '[:upper:]' '[:lower:]' | sed 's/[^a-z0-9]/-/g; s/--*/-/g; s/^-//; s/-$//'
}

BRANCH="auto/${TICKET_ID}-$(slugify "$TICKET_TITLE")"

git checkout -b "$BRANCH"

cat <<EOF_PROMPT | codex exec --json -a never -s workspace-write -C "$REPO_ROOT" - > "$LOG_JSON"
You are the nightly auto-compound agent for this repo.

Task:
- Implement sv task $TICKET_ID: "$TICKET_TITLE"
- Read details via: sv task show $TICKET_ID

Rules:
- Follow AGENTS.md, but use sv task for tracking (ignore tk references).
- Fix root cause, add tests where needed.
- Run: make check (use FORGE_TEST_SKIP_NETWORK=1 if needed).
- Commit with message including task id (example: "auto: <summary> ($TICKET_ID)").
- Do NOT push or open PR.
EOF_PROMPT

# Ensure clean working tree after agent run
DIRTY=$(git status --porcelain)
DIRTY_FILTERED=$(echo "$DIRTY" | rg -v "^\?\? (logs/|docs/review/)" || true)
if [[ -n "$DIRTY_FILTERED" ]]; then
  echo "Uncommitted changes detected after agent run." >&2
  echo "$DIRTY_FILTERED" >&2
  exit 1
fi

if ! git log -1 --pretty=%B | rg -q "$TICKET_ID"; then
  echo "Latest commit does not mention $TICKET_ID. Aborting." >&2
  exit 1
fi

if [[ -n "${FORGE_TEST_SKIP_NETWORK:-}" ]]; then
  FORGE_TEST_SKIP_NETWORK=1 make check
else
  make check
fi

if [[ "${COMPOUND_PUSH:-0}" == "1" ]]; then
  git push -u origin "$BRANCH"
  if command -v gh >/dev/null 2>&1; then
    gh pr create --draft --title "Compound: $TICKET_TITLE ($TICKET_ID)" --body "Auto-generated by nightly compound." --base main
  else
    echo "gh not found; skipping PR creation." >&2
  fi
else
  echo "COMPOUND_PUSH not set; skipping push/PR." >&2
fi
